import { test } from "@japa/runner";
import {
  generateSecret,
  generateToken,
  verifyToken,
  type SecretOptions,
} from "../lib/index.js";
import { decodeSecret } from "../lib/secret.js";

const options = { name: "My App", account: "user@example.com" };

test("generates a 160-bit TOTP secret with its URI and QR code", async ({
  expect,
}) => {
  const { secret, uri, qr } = await generateSecret(options);

  expect(secret).toMatch(/^[A-Z2-7]{32}$/);
  expect(uri).toBe(
    `otpauth://totp/My%20App:user%40example.com?secret=${secret}&issuer=My%20App`,
  );
  expect(qr.startsWith("data:image/png;base64,")).toBe(true);
});

test("writes the counter into HOTP URIs", async ({ expect }) => {
  const withCounter = await generateSecret({ ...options, counter: 5 }, "HOTP");
  expect(withCounter.uri).toBe(
    `otpauth://hotp/My%20App:user%40example.com?secret=${withCounter.secret}&issuer=My%20App&counter=5`,
  );

  const withoutCounter = await generateSecret(options, "HOTP");
  expect(withoutCounter.uri.endsWith("&counter=0")).toBe(true);
});

test("honors numberOfSecretBytes", async ({ expect }) => {
  const { secret } = await generateSecret({
    ...options,
    numberOfSecretBytes: 16,
  });
  expect(decodeSecret(secret)?.length).toBe(16);
});

test("uses every bit of the generated bytes", async ({ expect }) => {
  const bytes: number[] = [];
  for (let i = 0; i < 10; i++) {
    const { secret } = await generateSecret(options);
    bytes.push(...(decodeSecret(secret) ?? []));
  }
  expect(bytes).toHaveLength(200);
  expect(bytes.some((byte) => byte >= 0x80)).toBe(true);
});

test("generates secrets that verify their own tokens", async ({ expect }) => {
  const { secret } = await generateSecret(options);
  const result = generateToken(secret);
  expect(verifyToken(secret, result?.token)).toBe(true);
});

test("rejects secret sizes below 128 bits or not whole bytes", async ({
  expect,
}) => {
  for (const numberOfSecretBytes of [0, 10, 15, 16.5, -1, NaN]) {
    await expect(
      generateSecret({ ...options, numberOfSecretBytes }),
    ).rejects.toThrow(RangeError);
  }
});

test("rejects unknown types and invalid HOTP counters", async ({ expect }) => {
  await expect(generateSecret(options, "totp" as "TOTP")).rejects.toThrow(
    TypeError,
  );
  await expect(
    generateSecret({ ...options, counter: -1 }, "HOTP"),
  ).rejects.toThrow(RangeError);
});

test("only requires name and account", ({ expectTypeOf }) => {
  expectTypeOf(options).toExtend<SecretOptions>();
});
